package saga_msa.common;

public enum SageEventType {
    ORDER_CREATED,
    ORDER_CANCELLED,
    ORDER_REJECTED,
    PAYMENT_APPROVED,
    PAYMENT_REJECTED,
    ORDER_CANCELLATION_FAILED,
    ORDER_CANCELLATION_COMPLETED
}